MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "./ckpt/model_final_94dc52.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
DATASETS:
  # TRAIN: ("coco_2017_train_panoptic",)
  TRAIN: ("scannet_train_panoptic",)
  # TEST: ("coco_2017_val_panoptic_with_sem_seg",)  # to evaluate instance and semantic performance as well
  TEST: ("scannet_val_panoptic",)  # to evaluate instance and semantic performance as well
SOLVER:
  IMS_PER_BATCH: 6 #3
  BASE_LR: 0.0001
  STEPS: (327778, 355092)
  MAX_ITER: 368750
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: False # True
INPUT:
  IMAGE_SIZE: [480,640] # [256, 384] # h,w 480, 640    note 32x
  # IMAGE_SIZE: 512
  MIN_SCALE: 1.0 #0.1
  MAX_SCALE: 1.0 #2.0
  FORMAT: "RGB"
  # DATASET_MAPPER_NAME: "coco_panoptic_lsj"
  DATASET_MAPPER_NAME: "scannet"
TEST:
  # EVAL_PERIOD: 5000
  EVAL_PERIOD: 3000 #200 #100
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8 # 32
VERSION: 2

OUTPUT_DIR: "./output_debug_0809/"

PLANE_UNDERSTAND_ONLY: False

